FantasyKnessetWeb/FantasyKnessetWeb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'FantasyKnessetWeb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

fknesset/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('votes.urls', namespace="votes")),
    url(r'^admin/', include(admin.site.urls)),
    (r'^facebook/', include('django_facebook.urls')),
)

votes/urls.py
'''
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
'''


from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy

from votes import views

urlpatterns = patterns('',

    # Index view
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Candidate details view
    url(r'^candidate/(?P<pk>\d+)/$',
        views.CandidateView.as_view(),
        name='candidate'),

    # Candidate history (AJAX)
    url(r'^candidate/(?P<pk>\d+)/history$',
        views.candidate_history,
        name='candidate_history'),

    # Searching for candidate (AJAX)
    url(r'^search/$', views.search, name='autocomplete-search'),

    # Used for single vote (AJAX)
    url(r'^vote/$', views.vote, name='vote'),

    # Used for voting in a form. POST -> redirect
    url(r'^votes/$', views.batch_vote, name='batch_vote'),

    # Accounts administration
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/login/$',
        'django.contrib.auth.views.login',
        {'template_name': 'votes/login.html'}, name="login"),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('votes:index')}, name="logout"),

    # Adding candidates
    url(r'^add-candidate/new/$',
        views.CreateCandidateView.as_view(),
        name='add-candidate'),
    url(r'^add-candidate/$',
        views.add_candidate_from_fb,
        name='add-from-fb'),

    # Static content pages
    url(r'^feedback/$',
        views.FeedbackView.as_view(),
        name='feedback'),
    url(r'^work-in-progress/$',
        views.WorkInProgress.as_view(),
        name='work-in-progress'),
)

votes/forms.py
'''
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
'''


from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from votes.models import Candidate, Party


class CreateCandidateForm(forms.ModelForm):

    party = forms.ModelChoiceField(Party.objects.all(),
                                   initial=Party.objects.get(id=14),
                                   label=_('party'))

    class Meta:
        model = Candidate
        exclude = [
                   'voters',
                   'is_knesset_member',
                   'number_of_votes'
                   ]


class FacebookCreateCandidateForm(forms.Form):
    url = forms.URLField()
    party = forms.ModelChoiceField(Party.objects.all(),
                                   initial=Party.objects.get(id=14),
                                   label=_('party'))

votes/views.py
'''
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
'''

import json
import random
import re

from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.decorators import (login_required,
                                            permission_required)
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.utils.decorators import method_decorator
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect, render
from django.views import generic
from open_facebook.api import OpenFacebook
from open_facebook.exceptions import ParameterException

from votes.forms import (CreateCandidateForm,
                         FacebookCreateCandidateForm)
from votes.models import Candidate


User = get_user_model()


#----------------------------------------------------------
#       CUSTOM DECORATORS
#----------------------------------------------------------

def login_required_ajax(function=None, redirect_field_name=None):
    """
    Just make sure the user is authenticated to access a certain ajax
    view.

    Otherwise return a HttpResponse 401 - authentication required -
    instead of the 302 redirect of the original Django decorator.

    Solution from: http://stackoverflow.com/a/10031220/1224456
    """

    def _decorator(view_func):
        def _wrapped_view(request, *args, **kwargs):
            if request.user.is_authenticated():
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponse(status=401)
        return _wrapped_view

    if function:
        return _decorator(function)
    return _decorator


#----------------------------------------------------------
#       MAIN VIEWS
#----------------------------------------------------------

class IndexView(generic.TemplateView):
    template_name = 'votes/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['top20'] = sorted(Candidate.objects.all()[:20],
                                  key=lambda x: random.random()
                                  )
        context['rest100'] = sorted(Candidate.objects.all()[20:120],
                                    key=lambda x: x.name
                                    )
        context['fake5in'] = sorted(context['top20'],
                                    key=lambda x: random.random()
                                   )[:5]
        context['fake5out'] = sorted(context['rest100'],
                                     key=lambda x: random.random()
                                    )[:5]

        # adding faked time in top20
        for cand in context['top20']:
            cand.weeks = random.randrange(4) + 1

        return context


class CandidateView(generic.DetailView):
    model = Candidate


#----------------------------------------------------------
#       STATIC CONTENT VIEWS
#----------------------------------------------------------

class FeedbackView(generic.TemplateView):
    template_name = 'votes/feedback.html'


class WorkInProgress(generic.TemplateView):
    template_name = 'votes/work_in_progress.html'


#----------------------------------------------------------
#       DATA CREATION VIEWS (POSTS -> redirect)
#----------------------------------------------------------

# batch voting from index view
@login_required(login_url=reverse_lazy('votes:login'))
def batch_vote(request):

    if request.method == 'POST':

        batch_votes = request.POST.getlist('candidate_checkbox')

        votes_to_add = Candidate.objects.filter(pk__in=batch_votes) \
            .exclude(pk__in=request.user.candidate_set.all().
                     values('pk'))

        for candidate in votes_to_add:
            candidate.vote(request.user, upvote=True)

        votes_to_remove = request.user.candidate_set.all() \
            .exclude(pk__in=batch_votes)

        for candidate in votes_to_remove:
            candidate.vote(request.user, upvote=False)

    return redirect('votes:index')


# creating a candidate manually
class CreateCandidateView(generic.CreateView):
    model = Candidate
    form_class = CreateCandidateForm

    @method_decorator(permission_required('votes.add_candidate'))
    def dispatch(self, *args, **kwargs):
        return super(CreateCandidateView, self). \
            dispatch(*args, **kwargs)


# creating a candidate from facebook page
@permission_required('votes.add_candidate')
def add_candidate_from_fb(request):

    if request.method == 'POST':
        form = FacebookCreateCandidateForm(request.POST)
        if form.is_valid():
            fb = OpenFacebook()
            # fb_url = request.POST.get('fb_page')
            fb_url = form.cleaned_data['url']
            # party = Party.objects.get(id=request.POST.get('party'))
            party = form.cleaned_data['party']
            try:
                res = fb.get(fb_url, fields='name, website, picture.type(large)')
                sites = res.get('website', None).split(' ')
                for site in sites:
                    try:
                        if site == '':
                            continue
                        URLValidator(site)
                        val = site
                        break
                    except ValidationError as e:
                        print site, "is not a valid url"
                        continue

                # add another validation
                c = Candidate(name=res['name'],
                              image_url=res['picture']['data']['url'],
                              personal_site=val,
                              facebook_page=fb_url,
                              party=party)
                c.save()
                messages.info(request, "Added Successfully")
                return redirect(c.get_absolute_url())
            except ParameterException as e:
                messages.error(request, e.message)
    else:
        form = FacebookCreateCandidateForm()

    return render(request,
                  'votes/candidate_fb_form.html',
                  {'form': form})


#----------------------------------------------------------
#       AJAX / JSON VIEWS
#----------------------------------------------------------

# get candidate history json
def candidate_history(request, pk):
    c = Candidate.objects.get(pk=pk)
    return HttpResponse(c.history())


# for vote and unvote using AJAX
@login_required_ajax
def vote(request):

    results = dict(success=False)

    if request.method == 'POST':
        candidate = Candidate.objects.get(
            pk=request.POST.get('candidate_pk')
        )
        upvote = int(request.POST.get('upvote'))
        candidate.vote(request.user, upvote=upvote)
        results['success'] = True

    return HttpResponse(json.dumps(results))


# for searching via autocomplete
def search(request):
        search_str = request.GET.get('item')
        str_to_match = re.compile(r'^'+search_str+'|([\u05D0-\u05EA]+(\s|[^\u05D0-\u05EA])+)'+search_str)
        results = Candidate.objects.filter(name__regex=str_to_match.pattern)
        data = []
        for candidate in results:
            url = candidate.get_absolute_url()
            name = candidate.name
            data.append(dict(name=name, url=url))

        return HttpResponse(json.dumps(data))


#----------------------------------------------------------
#       ACCOUNTS MANAGEMENT
#----------------------------------------------------------

def register(request):

    error = None

    if request.method == 'POST':

        # extract form parameters
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        # continue only if the username is unique
        if len(User.objects.filter(username=username)) == 0:

            # create and save the user to the db
            user = User.objects.create_user(username, email, password)
            user.save()

            # authenticate the user, log in and redirect
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('votes:index')

        # if username is not unique set the error
        error = 'Username already exist'

    context = dict(error=error)
    context.update(csrf(request))
    return render_to_response('votes/register.html', context)

votes/templates/votes/candidate_detail.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->



{% extends "base.html" %}
{% load static %}
{% load voting %}
{% load i18n %}

{% block content %}

<div class="container">

	<div class="row">
		<div class="col-md-9">
			<h1>{{ object }}</h1>
			<p class="lead">{{ object.party }}</p>
			{% if object.is_knesset_member %}
				<p class="lead">{% trans "Knesset member" %}</p>
			{% endif %}
		</div>
		<div class="col-md-3">
				<button class="btn btn-block btn-candidate" pk="{{ candidate.pk }}" upvote="{{ user|button_value:candidate }}"></button>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			<div><!-- buttons -->
				{% if object.personal_site %}
					<a class="btn btn-default" href="{{ object.personal_site }}">{% trans "Personal site" %}</a>	
				{% endif %}
				{% if object.facebook_page %}
					<a class="btn btn-default" href="{{ object.facebook_page }}">{% trans "Facebook page" %}</a>	
				{% endif %}
				{% if object.wikpedia_article %}
					<a class="btn btn-default" href="{{ object.wikpedia_article }}">{% trans "Wikipedia" %}</a>
				{% endif %}
				{% if object.open_k_url %}
					<a class="btn btn-default" href="{{ object.open_k_url }}">{% trans "OpenKnesset page" %}</a>
				{% endif %}
			</div>
			<div dir="ltr" class="well">
				<!-- history -->
				<div id="chart" ></div>
			</div>
		</div>
		<div class="col-md-3">
			{% if object.image_url %}
				<img src="{{ object.image_url }}" class="img-thumbnail">
			{% endif %}
		</div>
	</div>

</div><!-- /container -->

{% endblock %}

{% block load_scripts %}

<!-- chart script -->
<script src="{% static 'votes/js/chart.js' %}"></script>

{% endblock %}

votes/templates/votes/candidate_fb_form.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
	<div class="well form-signin">

		<form role="form" method="post" next="/">
			{% csrf_token %}
			<h2 class="form-signin-heading">{% trans "Paste Candidates Facebook Page Link" %}</h2>
			<table>
				{{ form.as_table}}
			</table>
			<input class="btn btn-lg btn-primary btn-block" type="submit" value="{% trans "Save" %}" />
		</form>

	</div>
</div>

{% endblock %}

votes/templates/votes/candidate_form.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
	<div class="well">

		<h2 class="form-signin-heading">{% trans "Enter Candidate Data" %}</h2>
		<div class="form-group">
			<form class="form-signin" role="form" method="post" next="/">
				{% csrf_token %}
				<table>
					{{ form.as_table}}
				</table>
				<input class="btn btn-primary" type="submit" name="Save" value="{% trans 'Submit' %}"
					style="text-align: center" />
			</form>
		</div>
	</div>
</div>

{% endblock %}

votes/templates/votes/feedback.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
	<div class="well">

		<h1>{% trans "Feedbacks are always welcome" %}</h1>
		<p>
			{% blocktrans %}A very pretty form will appear here shortly, meanwhile you are more then welcome to send your feedback to {% endblocktrans %}
			<a href="mailto:games.of.knesset@gmail.com">games.of.knesset@gmail.com</a>
		</p>

	</div>
</div>

{% endblock %}

votes/templates/votes/index.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load static %}
{% load voting %}
{% load i18n %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
{% if user.is_authenticated %}
{% else %}
	<div class="jumbotron">
		<div class="container">
			<h1>{% trans "Hello, Voters!" %}</h1>
			<p>{% trans "Choose your own Knesset Members, Check the differences between our representitves and what people accually want!" %}</p>
		</div>
	</div>
{% endif %}

<div class="container">

	<!-- Top 20 Candidates -->
	<div class="row">
		<div class="col-md-9 col-xs-12 text-center">
			<h1 align="center">{% trans "Top 20 Candidates" %}</h1>
			<div class="row">
				{% for candidate in top20 %}
					<div class="col-md-4 col-xs-6 text-center">
						<div class="well dense">
							<div class="row">
								<div class="col-xs-1 center-cropped center" style="background-image: url('{{ candidate.image_url}}');"></div>
								<div class="with-margins">
									<p><b><a href="{{ candidate.get_absolute_url }}">{{ candidate.name }}</a></b></p>
									<p>{{ candidate.weeks }} {% trans "weeks in top 20!" %}</p>
									<p><button class="align-bottom btn btn-candidate" pk="{{ candidate.pk }}" upvote="{{ user|button_value:candidate }}"></button></p>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
		<div class="col-md-3 col-xs-12">
			<h1 align="center">{% trans "New in top 20" %}</h1>
			<h4 align="center">{% trans "Changes since last week" %}</h4>
			<ol class="list-group">
			{% for candidate in fake5in %}
				<li class="list-group-item" style="background-color:rgba(100, 250, 100, 0.4)">
					<a href="{{ candidate.get_absolute_url }}">{{ candidate.name }}</a>
				</li>
			{% endfor %}
			</ol>
		</div>
		<div class="col-md-3 col-xs-12">
			<h1 align="center">{% trans "Out of top 20" %}</h1>
			<h4 align="center">{% trans "Changes since last week" %}</h4>
			<ol class="list-group">
			{% for candidate in fake5out %}
				<li class="list-group-item" style="background-color:rgba(250, 50, 50, 0.4)">
					<a href="{{ candidate.get_absolute_url }}">{{ candidate.name }}</a>
				</li>
			{% endfor %}
			</ol>
		</div>
	</div>

	<!-- Rest 100 Candidates -->
	<h1 align="center">{% trans "Rest 100 Candidates" %}</h1>
	<form role="form" method="post" action="{% url 'votes:batch_vote' %}" >
		{% csrf_token %}
		<div class="row">
			{% for candidate in rest100 %}
				<div class="col-md-3 col-xs-6">
					{% if user|voted_for:candidate %}
						<input type="checkbox" name="candidate_checkbox" value="{{ candidate.pk }}" checked> <a href="{% url 'votes:candidate' candidate.pk %}">{{ candidate.name }}</a>
					{% else %}
						<input type="checkbox" name="candidate_checkbox" value="{{ candidate.pk }}"> <a href="{% url 'votes:candidate' candidate.pk %}">{{ candidate.name }}</a>
					{% endif %}
				</div>
			{% endfor %}
			{% for candidate in top20 %}
				{% if user|voted_for:candidate %}
					<input type="hidden" name="candidate_checkbox" value="{{ candidate.pk }}">
				{% endif %}
			{% endfor %}     
		</div>
		<input class="btn btn-primary btn-block" type="submit" value="{% trans "VOTE" %}" />
	</form>

</div><!-- /container -->

{% endblock %}

votes/templates/votes/login.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load i18n %}

<link href="{{ STATIC_URL }}css/facebook.css" type="text/css" rel="stylesheet" media="all" />
{% include 'django_facebook/_facebook_js.html' %}

{% block content %}

<div class="container">
	<div class="well form-signin">

		<!-- Log in with auth user -->
		{% if form.errors %}
			<p>{% trans "Your username and password didn't match. Please try again." %}</p>
		{% endif %}

		<form class="form-signin" role="form" method="post">
			<h2 class="form-signin-heading">{% trans "Please login" %}</h2>
			{% csrf_token %}
			<input type="text" class="form-control" placeholder="{% trans "Username" %}" name="username" required autofocus>
			<input type="password" class="form-control" placeholder="{% trans "Password" %}" name="password" required>
			<input class="btn btn-lg btn-primary btn-block" type="submit" value="{% trans "Sign in" %}" />
			<input type="hidden" name="next" value="{{ next }}" />
		</form>

		<!-- Log in with facebook -->
		<div class="text-center">
			<form action="{% url 'facebook_connect' %}?facebook_login=1" method="post">
				{% csrf_token %}
				<input type="hidden" value="{{ request.path }}" name="next" />
				<input type="hidden" value="{{ request.path }}" name="register_next" />
				<input type="hidden" value="{{ request.path }}" name="error_next" />
				<input onclick="F.connect(this.parentNode); return false;" type="image" src="{{ STATIC_URL }}django_facebook/images/facebook_login.png" />
			</form>
		</div>

		<div class="lead">
			<p>{% trans "Don't have an account? create one" %} <a href="{% url 'votes:register' %}">{% trans "here" %}</a></p>
		</div>
	</div>
</div>

{% endblock %}

votes/templates/votes/register.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
	<div class="well form-signin">

		{% if error %}
			<div style="color: red">{{ error }}</div>
		{% endif %}

		<form class="form-signin" role="form" method="POST">
			{% csrf_token %}
			<h2 class="form-signin-heading">{% trans "Please register" %}</h2>
			<input type="text" class="form-control" placeholder="{% trans "Username" %}" name="username" required autofocus>
			<input type="password" class="form-control" placeholder="{% trans "Password" %}" name="password" required>
			<input class="btn btn-lg btn-primary btn-block" type="submit" value="{% trans "Sign up" %}" />
			<input type="hidden" name="next" value="{% url 'votes:index' %}" />
		</form>

	</div>
</div>

{% endblock %}

votes/templates/votes/work_in_progress.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
	<div class="well">

		<h1>{% trans "The page is still in construction" %}</h1>
		<p>
			{% blocktrans %}Visit again soon to see this cool feature in action!{% endblocktrans %}
		</p>

	</div>
</div>

{% endblock %}