FantasyKnessetWeb/FantasyKnessetWeb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'FantasyKnessetWeb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

fknesset/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('votes.urls', namespace="votes")),
    url(r'^admin/', include(admin.site.urls)),
    (r'^facebook/', include('django_facebook.urls')),
)

votes/urls.py
'''
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
'''


from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy

from votes import views

urlpatterns = patterns('',

    # Index view
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Candidate details view
    url(r'^candidate/(?P<pk>\d+)/$',
        views.CandidateView.as_view(),
        name='candidate'),

    # Candidate history (AJAX)
    url(r'^candidate/(?P<pk>\d+)/history$',
        views.candidate_history,
        name='candidate_history'),

    # Searching for candidate (AJAX)
    url(r'^search/$', views.search, name='autocomplete-search'),

    # Used for single vote (AJAX)
    url(r'^vote/$', views.vote, name='vote'),

    # Used for voting in a form. POST -> redirect
    url(r'^votes/$', views.batch_vote, name='batch_vote'),

    # Accounts administration
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/login/$',
        'django.contrib.auth.views.login',
        {'template_name': 'votes/login.html'}, name="login"),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout',
        {'next_page': reverse_lazy('votes:index')}, name="logout"),

    # Adding candidates
    url(r'^add-candidate/new/$',
        views.CreateCandidateView.as_view(),
        name='add-candidate'),
    url(r'^add-candidate/$',
        views.add_candidate_from_fb,
        name='add-from-fb'),

    # Static content pages
    url(r'^feedback/$',
        views.FeedbackView.as_view(),
        name='feedback'),
    url(r'^work-in-progress/$',
        views.WorkInProgress.as_view(),
        name='work-in-progress'),
)

votes/models.py
'''
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
'''


import json

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _


class Party(models.Model):
    name = models.CharField(_('name'), max_length=200)
    official_site = models.URLField(_('official site'), null=True, blank=True)
    facebook_page = models.URLField(_('facebook_page'), null=True, blank=True)
    wikpedia_article = models.URLField(
        _('wikipedia_article'), null=True, blank=True)
    wikpedia_url = models.URLField(_('wikipedia_url'), null=True, blank=True)
    open_k_url = models.URLField(_('open_knesset_url'), null=True, blank=True)
    logo_url = models.URLField(_('logo_url'), null=True, blank=True)

    def __unicode__(self):
        return self.name


class Candidate(models.Model):
    party = models.ForeignKey(Party,
                              verbose_name=_('party'))
    voters = models.ManyToManyField(
        settings.AUTH_USER_MODEL, null=True, blank=True
    )
    name = models.CharField(_('name'), max_length=200)
    number_of_votes = models.PositiveIntegerField(default=0)
    is_knesset_member = models.BooleanField(default=False)
    personal_site = models.URLField(_('personal site'), null=True, blank=True)
    facebook_page = models.URLField(_('facebook_page'), null=True, blank=True)
    wikpedia_article = models.URLField(
        _('wikipedia_article'), null=True, blank=True)
    wikpedia_url = models.URLField(_('wikipedia_url'), null=True, blank=True)
    open_k_url = models.URLField(_('open_knesset_url'), null=True, blank=True)
    image_url = models.URLField(
        _('picture_url'), null=True, blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse('votes:candidate', args=(self.id,))

    def __unicode__(self):
        return self.name

    def vote(self, user, upvote):
        if upvote and user not in self.voters.all():
            self.voters.add(user)
            self.number_of_votes = models.F('number_of_votes') + 1
        elif not upvote and user in self.voters.all():
            self.voters.remove(user)
            self.number_of_votes = models.F('number_of_votes') - 1
        
        self.save()

        Log.log(self.pk)

    class Meta:
        ordering = ['-number_of_votes']

    def history(self):
        '''
        Returns a json with the candidate history log.
        '''

        logs = Log.objects.filter(candidate__pk=self.pk)
        fmt = "%Y-%m-%d %H:%M"
        history = [dict(timestamp=log.timestamp.strftime(fmt),
                        value=log.number_of_votes) \
                   for log in logs]

        # always add current number of votes
        history.append(dict(
            timestamp=timezone.now().strftime(fmt),
            value=self.number_of_votes)
        )

        # history normalization
        max_item = max(history, key=lambda x: x['value'])
        if max_item['value'] != 0:
            for item in history:
                item['value'] /= float(max_item['value'])

        return json.dumps(history)


class Log(models.Model):
    candidate = models.ForeignKey(Candidate)
    number_of_votes = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'candidate: {}, votes: {}, timestamp: {}' \
            .format(self.candidate.name,
                    self.number_of_votes,
                    self.timestamp.strftime('%Y-%m-%d %H:%M')
                    )

    @classmethod
    def log(cls, pk):
        c = Candidate.objects.get(pk=pk)
        cls.objects.create(candidate=c,
                           number_of_votes=c.number_of_votes)

votes/views.py
'''
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
'''

import json
import random
import re

from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.decorators import (login_required,
                                            permission_required)
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.utils.decorators import method_decorator
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect, render
from django.views import generic
from open_facebook.api import OpenFacebook
from open_facebook.exceptions import ParameterException

from votes.forms import (CreateCandidateForm,
                         FacebookCreateCandidateForm)
from votes.models import Candidate


User = get_user_model()


#----------------------------------------------------------
#       CUSTOM DECORATORS
#----------------------------------------------------------

def login_required_ajax(function=None, redirect_field_name=None):
    """
    Just make sure the user is authenticated to access a certain ajax
    view.

    Otherwise return a HttpResponse 401 - authentication required -
    instead of the 302 redirect of the original Django decorator.

    Solution from: http://stackoverflow.com/a/10031220/1224456
    """

    def _decorator(view_func):
        def _wrapped_view(request, *args, **kwargs):
            if request.user.is_authenticated():
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponse(status=401)
        return _wrapped_view

    if function:
        return _decorator(function)
    return _decorator


#----------------------------------------------------------
#       MAIN VIEWS
#----------------------------------------------------------

class IndexView(generic.TemplateView):
    template_name = 'votes/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['top20'] = sorted(Candidate.objects.all()[:20],
                                  key=lambda x: random.random()
                                  )
        context['rest100'] = sorted(Candidate.objects.all()[20:120],
                                    key=lambda x: x.name
                                    )
        context['fake5in'] = sorted(context['top20'],
                                    key=lambda x: random.random()
                                   )[:5]
        context['fake5out'] = sorted(context['rest100'],
                                     key=lambda x: random.random()
                                    )[:5]

        # adding faked time in top20
        for cand in context['top20']:
            cand.weeks = random.randrange(4) + 1

        return context


class CandidateView(generic.DetailView):
    model = Candidate


#----------------------------------------------------------
#       STATIC CONTENT VIEWS
#----------------------------------------------------------

class FeedbackView(generic.TemplateView):
    template_name = 'votes/feedback.html'


class WorkInProgress(generic.TemplateView):
    template_name = 'votes/work_in_progress.html'


#----------------------------------------------------------
#       DATA CREATION VIEWS (POSTS -> redirect)
#----------------------------------------------------------

# batch voting from index view
@login_required(login_url=reverse_lazy('votes:login'))
def batch_vote(request):

    if request.method == 'POST':

        batch_votes = request.POST.getlist('candidate_checkbox')

        votes_to_add = Candidate.objects.filter(pk__in=batch_votes) \
            .exclude(pk__in=request.user.candidate_set.all().
                     values('pk'))

        for candidate in votes_to_add:
            candidate.vote(request.user, upvote=True)

        votes_to_remove = request.user.candidate_set.all() \
            .exclude(pk__in=batch_votes)

        for candidate in votes_to_remove:
            candidate.vote(request.user, upvote=False)

    return redirect('votes:index')


# creating a candidate manually
class CreateCandidateView(generic.CreateView):
    model = Candidate
    form_class = CreateCandidateForm

    @method_decorator(permission_required('votes.add_candidate'))
    def dispatch(self, *args, **kwargs):
        return super(CreateCandidateView, self). \
            dispatch(*args, **kwargs)


# creating a candidate from facebook page
@permission_required('votes.add_candidate')
def add_candidate_from_fb(request):

    if request.method == 'POST':
        form = FacebookCreateCandidateForm(request.POST)
        if form.is_valid():
            fb = OpenFacebook()
            # fb_url = request.POST.get('fb_page')
            fb_url = form.cleaned_data['url']
            # party = Party.objects.get(id=request.POST.get('party'))
            party = form.cleaned_data['party']
            try:
                res = fb.get(fb_url, fields='name, website, picture.type(large)')
                sites = res.get('website', None).split(' ')
                for site in sites:
                    try:
                        if site == '':
                            continue
                        URLValidator(site)
                        val = site
                        break
                    except ValidationError as e:
                        print site, "is not a valid url"
                        continue

                # add another validation
                c = Candidate(name=res['name'],
                              image_url=res['picture']['data']['url'],
                              personal_site=val,
                              facebook_page=fb_url,
                              party=party)
                c.save()
                messages.info(request, "Added Successfully")
                return redirect(c.get_absolute_url())
            except ParameterException as e:
                messages.error(request, e.message)
    else:
        form = FacebookCreateCandidateForm()

    return render(request,
                  'votes/candidate_fb_form.html',
                  {'form': form})


#----------------------------------------------------------
#       AJAX / JSON VIEWS
#----------------------------------------------------------

# get candidate history json
def candidate_history(request, pk):
    c = Candidate.objects.get(pk=pk)
    return HttpResponse(c.history())


# for vote and unvote using AJAX
@login_required_ajax
def vote(request):

    results = dict(success=False)

    if request.method == 'POST':
        candidate = Candidate.objects.get(
            pk=request.POST.get('candidate_pk')
        )
        upvote = int(request.POST.get('upvote'))
        candidate.vote(request.user, upvote=upvote)
        results['success'] = True

    return HttpResponse(json.dumps(results))


# for searching via autocomplete
def search(request):
        search_str = request.GET.get('item')
        str_to_match = re.compile(r'^'+search_str+'|([\u05D0-\u05EA]+(\s|[^\u05D0-\u05EA])+)'+search_str)
        results = Candidate.objects.filter(name__regex=str_to_match.pattern)
        data = []
        for candidate in results:
            url = candidate.get_absolute_url()
            name = candidate.name
            data.append(dict(name=name, url=url))

        return HttpResponse(json.dumps(data))


#----------------------------------------------------------
#       ACCOUNTS MANAGEMENT
#----------------------------------------------------------

def register(request):

    error = None

    if request.method == 'POST':

        # extract form parameters
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        # continue only if the username is unique
        if len(User.objects.filter(username=username)) == 0:

            # create and save the user to the db
            user = User.objects.create_user(username, email, password)
            user.save()

            # authenticate the user, log in and redirect
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('votes:index')

        # if username is not unique set the error
        error = 'Username already exist'

    context = dict(error=error)
    context.update(csrf(request))
    return render_to_response('votes/register.html', context)

votes/templates/base.html
<!--
Copyright 2014 Ari Meidan and Tom Gurion

This file is part of "Games of Knesset".

"Games of Knesset" is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

"Games of Knesset" is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with "Games of Knesset".  If not, see <http://www.gnu.org/licenses/>.
-->


<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load facebook_image %}

<html>
<head>

<title>{% trans "Games of Knesset" %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Bootstrap -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-rtl.min.css' %}" rel="stylesheet">

<!-- jQuery UI -->
<link href="{% static 'jquery/css/jquery-ui.css' %}" rel="stylesheet">

<!-- Games of Knesset stylesheet -->
<link href="{% static 'votes/css/style.css' %}" rel="stylesheet">
</head>
<body>

<!-- navbar -->
<div class="navbar navbar-inverse navbar-static-top navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">{% trans "Toggle navigation" %}</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'votes:index' %}">
				<img  src="{% static 'votes/graphics/logo.png' %}">
				{% trans "Games of Knesset" %}
			</a>
		</div>

		<div class="navbar-collapse collapse">

			<!-- navbar right align -->
			<ul class="nav navbar-nav">

				{% if perms.votes.add_candidate %}
					<li><a href="{% url 'votes:add-from-fb' %}">{% trans "Add candidate" %}</a></li>
				{% endif %}
				<li><a href="{% url 'votes:work-in-progress' %}">{% trans "About" %}</a></li>
				<li class="navbar-form">
					<input id="candidate-search" type="text" class="form-control" placeholder="{% trans "Search" %}">
				</li>
			</ul>

			<!-- navbar left align -->
			<ul class="nav navbar-nav navbar-left">

				{% if user.is_authenticated %}

					<!-- Authenticated dropdown -->
					<li class="dropdown">
						<a href="#" data-toggle="dropdown">{% trans "Hello" %} {{ user.username }} <b class="caret"></b></a>
						<ul class="dropdown-menu pull-left">
							<li><a href="{% url 'votes:work-in-progress' %}">{% trans "Profile" %}</a></li>
							<li class="divider"></li>
							<li><a href="{% url 'votes:logout' %}">{% trans "Logout" %}</a></li>
						</ul>
					</li>

					<!-- Facebook picture -->
					{% if user.access_token %}
						<li><img src="{{ user|fb_image }}" class="img-circle" style="height: 50px"></li>
					{% endif %}

				{% else %}<!-- not authenticated -->

					<!-- Register -->
					<!-- TODO enable registration after email server setup!!! -->
					<!-- <li>
						<a href="{% url 'votes:register' %}">{% trans "Register" %}</a>
					</li> -->
					<!-- Login dropdown -->
					<li class="dropdown">
						<a href="#" data-toggle="dropdown">{% trans "Login" %} <b class="caret"></b></a>
						<div class="dropdown-menu pull-left">
							<form class="form-signin" role="form" method="post" action="{% url 'votes:login' %}">
								{% csrf_token %}
								<input type="text" class="form-control" placeholder="{% trans "Username" %}" name="username" required autofocus>
								<input type="password" class="form-control" placeholder="{% trans "Password" %}" name="password" required>
								<input class="btn btn-primary form-control" type="submit" value="{% trans "Sign in" %}" />
							</form>
							<!-- Log in with facebook -->
							<form action="{% url 'facebook_connect' %}?facebook_login=1" method="post">
								{% csrf_token %}
								<input type="hidden" value="{{ request.path }}" name="next" />
								<input type="hidden" value="{{ request.path }}" name="register_next" />
								<input type="hidden" value="{{ request.path }}" name="error_next" />
								<input onclick="F.connect(this.parentNode); return false;" type="image" src="{{ STATIC_URL }}django_facebook/images/facebook_login.png"/>
							</form>
						</div>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</div><!-- navbar -->

<!-- Still in alpha note -->
<div style="background-color:rgba(200, 0, 0, 0.5)">
	<div class="container text-center">
		{% trans "We are still in alpha. Lots of great features on the way!" %}
	</div>
</div>

<!-- error messages -->
{% for message in messages %}
	<div class="container">
		<div class="alert{% if message.tags %} alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}{% endif %} alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			{{ message|safe }}
		</div>
	</div>
{% endfor %}

{% block content %}

{% endblock %}

<!-- floating feedback link -->
<a id="floating_link" href="{% url 'votes:feedback' %}"></a>

<!-- jQuery (necessary for Bootstrap's JS plugins) -->
<script src="{% static 'jquery/jquery-2.1.0.min.js' %}"></script>
<!-- jQuery plugin to get and set cookies, used for csrf manipulations -->
<script src="{% static 'jquery/jquery.cookie.js' %}"></script>
<!-- jQuery UI, used for candidate autocomplete -->
<script src="{% static 'jquery/jquery-ui.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- D3 scripts -->
<script src="{% static 'js/d3.v3.min.js' %}"></script>

<!-- Custom script for ajax voting -->
<script>
	$.config = {
		search_url: "{% url 'votes:autocomplete-search' %}",
		login_url: "{% url 'votes:login' %}",
		vote_url: "{% url 'votes:vote' %}",
		vote_text: ["{% trans 'UnVote' %}", "{% trans 'Vote' %}"],
		btn_class: ["btn-primary", "btn-default"],
	}
</script>
<script src="{% static 'votes/js/votes.js' %}"></script>
<script src="{% static 'votes/js/search_candidate.js' %}"></script>


<!-- Custom made scripts should be loaded last -->
{% block load_scripts %}

{% endblock %}

</body>
</html>

votes/templates/register_login_panel.html
{% load i18n %}

{% load facebook_image %}
<div class="navbar-collapse collapse">
	<div class="navbar-left navbar-form">
		{% if user.is_authenticated %}
			<a  href="{% url 'votes:logout' %}" class="btn btn-success">{% trans "Logout" %}</a>
			{% if user.access_token %}
		    <img src="{{ user|fb_image }}" class="img-circle">
			{% endif %}
		{% else %}
			<a  href="{% url 'votes:register' %}" class="btn btn-success">{% trans "Register" %}</a>
			<a  href="{% url 'votes:login' %}" class="btn btn-success">{% trans "Login" %}</a>
		{% endif %}
	</div>
</div>

votes/templates/register_signin.html
<div class="navbar-collapse collapse">
	<div class="navbar-right navbar-form">
		{% if user_signed_in %}
			<a  class="btn btn-success">Logout</a>
		{% else %}
			<a  href="{% url 'votes:register' %}" class="btn btn-success">Register</a>
			<a  href="{% url 'votes:login' %}" class="btn btn-success">Sign in</a>
		{% endif %}
	</div>
</div>